# -*- coding: utf-8 -*-
bengali = {
           'magazine_name': u'মাসিক আলকাউসার ',
           'magazine_slogan': u'গবেষণামূলক উচ্চতর শিক্ষাপ্রতিষ্ঠান মারকাযুদ্ দাওয়াহ আলইসলামিয়া ঢাকা-এর মুখপত্র',
           'authors': u'লেখকবৃন্দ',
           'categories': u'এ সংখ্যায়  আছে',
           'archives': u'পুরোনো সংখ্যা',
           'back_issue': u'পুরোনো সংখ্যা',
           'section': u'বিভাগ',
           'all_sections': u'সকল বিভাগসমূহ',
           'aboutus': u'পরিচিতি',
           'contactus': u'যোগাযোগ',
           'home': u'হোম',
           'previous': u'পূর্ববর্তী',
           'next': u'পরবর্তী',
           'find': u'খুজুন',
           'year': u'বর্ষ',
           'number': u'সংখ্যা',
           'tags_cloud': u'ট্যাগ',
           'all_tags': u'সকল ট্যাগ',
           'tag': u'ট্যাগ',
           'weblinks': u'প্রয়োজনীয় কিছু সাইট',
           'welcome': u'আসসালামু আলাইকুম',
           'subject': u'বিষয়',
           'question': u'প্রশ্ন',
           'type_in_question': u'আপনার মূল্যবান প্রশ্নটি বাংলা অথবা ইংরেজীতে টাইপ করুন',
           'ask_question': u'ফতওয়া জিজ্ঞাসা করুন',
           'submit': u'প্রেরণ করুন',
           'enter_email': u'ইমেইল',
           'question_answer': u'আপনি যা জানতে চেয়েছেন',
           'current_issue': u'চলতি সংখ্যা',
           'sign_in': u'লগইন',
           'sign_up': u'ফাতওয়া জানতে রেজিষ্টার করুন',
           'sign_out': u'লগ আউট',
           'manage_account': u'একাউন্ট',
           'related_articles': u'লেখা সমূহ',
           'read_more': u'বিস্তারিত',
           'other_authors': u'অন্যান্য লেখকবৃন্দ',
           'salam' : u'আসসালামু আলাইকুম',
           'answer': u'উত্তর',
           'problem': u'সমস্যা',
           'advice': u'পরামর্শ',
           'name': u'নাম',
           'url': u'ওয়েব ঠিকানা',
           'other_articles_from_this_issue': u'এ সংখ্যার অন্যান্য আর্টিকেল',
           'popular_articles': u'সর্বাধিক পঠিত',
           'main_menu': [
                    {'name': u'চলতি সংখ্যা', 'link': '/', 'is_active': True},
                    {'name': u'পুরোনো সংখ্যা', 'link': '/issues/archives', 'is_active': True},
                    {'name': u'বিভাগসমূহ', 'link': '/sections', 'is_active': True},
                    {'name': u'লেখকবৃন্দ', 'link': '/authors', 'is_active': True},
                    {'name': u'ফাতওয়া', 'link': '/section/question-answer', 'is_active': False},
                    {'name': u'পরিচিতি', 'link': '/about_us', 'is_active': True},
                    {'name': u'যোগাযোগ', 'link': '/contact_us', 'is_active': True},
                    {'name': u'গ্রাহক ও এজেন্ট', 'link': '/subscribe-agent', 'is_active': True},
                    {'name': u'মতামত', 'link': '/feedback', 'is_active': True, 'is_last': True }
              ]
}

english = {
           'magazine_name': u'The monthly Alkawsar',
           'magazine_slogan': u'Markazudda Al-Islamia Dhaka',
           'authors': u'Authors',
           'categories': u'Sections',
           'archives': u'Archives',
           'back_issue': u'Back Issue',
            'section': u'Section',
           'all_sections': u'All Sections',
           'aboutus': u'About us',
           'contactus': u'Contact us',
           'home': u'Home',
           'previous': u'Previous',
           'next': u'Next',
           'find': u'Find here',
           'year': u'Year',
           'number': u'Issue',
           'tags_cloud': u'Tag Cloud',
           'tag': u'Tag',
           'all_tags': u'All Tags',
           'weblinks': u'Resources',
           'welcome': 'Assalamu Alikum',
           'subject': u'Subject',
           'question': u'Question',
           'answer': u'Answer',
           'ask_question': u'Ask for fatawa',
           'type_in_question': u'Type in your valuable question in English or Bengali',
           'submit': 'Submit',
           'enter_email': u'Enter Your Email',
           'question_answer': u'Questions & Answers',
           'current_issue': u'Current Issue',
           'sign_in': u'Login In',
           'sign_up': u'Register!',
           'sign_out': u'Log Out',
           'manage_account': u'My Account',
           'related_articles': u'RELATED ARTICLES',
           'read_more': u'Read More',
           'other_authors': u'Other Authors',
           'salam' : u'Assalamu Alikum',
           'problem': u'Problem',
           'advice': u'Advice',
           'other_articles_from_this_issue': u'More Articles From This Issue',
           'popular_articles': u'Most Read',
            'main_menu': [
                         {'name': u'Latest Articles', 'link': '/', 'is_active': True},
                         {'name': u'Archive', 'link': '/archives/articles', 'is_active': False},
                         {'name': u'Sections', 'link': '/sections', 'is_active': False},
                         {'name': u'Authors', 'link': '/authors', 'is_active': True},
                         {'name': u'Fatawas', 'link': '/section/question-answer', 'is_active': False},
                         {'name': u'About', 'link': '/about_us', 'is_active': True},
                         {'name': u'Contact', 'link': '/contact_us', 'is_active': True},
                         {'name': u'Feedback', 'link': '/feedback', 'is_active': True, 'is_last': True}
                        ]
           
}